name: Go Build and Publish Release

on:
  workflow_dispatch:
    inputs:
      tags:
        description: "Version tags"
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: "1.23.3"

    - name: Build Go project
      run: |
        # Linux builds
        GOOS=linux CGO_ENABLED=0 GOARCH=amd64 go build -o command-linux-amd64.so
        GOOS=linux CGO_ENABLED=0 GOARCH=arm64 go build -o command-linux-arm64.so
        
        # Windows build
        GOOS=windows CGO_ENABLED=0 GOARCH=amd64 go build -o command-windows-amd64.dll
        
        chmod +x command-*.*
        ls -lart

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: yao-command-plugin
        files: |
          *.so
          *.dll
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Get Release URL
      run: |
        echo "Release URL: ${{ steps.create_release.outputs.upload_url }}"